name: Run playwright tests

on: push

jobs:
    run-tests:
        name: Run Playwright tests
        runs-on: ubuntu-latest
        container:
            image: node:20-bookworm
            volumes:
                - ${{ github.workspace }}:/app
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Installing deps
              run: npm ci

            - name: Installing Playwright
              run: npx playwright install --with-deps

            - name: Test e2e
              env:
                  # Fix firefox crash when run with Github actions
                  # Details: https://github.com/microsoft/playwright/issues/6500#issuecomment-838515115`
                  HOME: /root
              run: npx playwright test
